Repository CodingTestKiller/Season2, pull requests merged in 2023-07, with the labels that each got.

#22 [김민수] / 가르침-17453, 두개의문-17453, 원숭이스포츠-16438, 조각움직이기-1035
  비트마스킹/가르침-1062/kmsu44.py
  비트마스킹/두개의문-17453/kmsu44.py
  비트마스킹/원숭이스포츠-16438/kmsu44.py
  비트마스킹/조각움직이기-1035/kmsu44.py
Labels: 비트마스킹

#25 [김경원] / 우체국-2141, 짝수팰린드롬-21924, 크게만들기-2812
  그리디/우체국-2141/masonkimseoul.py
  그리디/짝수팰린드롬-21925/masonkimseoul.py
  그리디/크게만들기-2812/masonkimseoul.py
Labels: 그리디

#23 [김민수] / 우체국-2141, 짝수팰린드롬-21924, 크게만들기-2812
  그리디/우체국-2141/kmsu44.py
  그리디/짝수팰린드롬-21925/kmsu44.py
  그리디/크게만들기-2812/kmsu44.py
Labels: 그리디

#24 [이우식] / 우체국-2141, 짝수팰린드롬-21924, 크게만들기-2812
  그리디/우체국-2141/yireal.py
  그리디/짝수팰린드롬-21925/yireal.py
  그리디/크게만들기-2812/yireal.py
  비트마스킹/가르침-1062/yireal.py
  비트마스킹/두개의문-17453/yireal.py
  비트마스킹/원숭이스포츠-16438/yireal.py
Labels: 그리디

#32 [정재경] / ㅋㅋ루ㅋㅋ-20442, 가짝연부-22862, 합이0인네정수-7453
  투포인터/ㅋㅋ루ㅋㅋ-20442/therealjamesjung.py
  투포인터/가짝연부-22862/therealjamesjung.py
  투포인터/합이0인네정수/therealjamesjung.py
Labels: 투포인터

#30 [김경원] / ㅋㅋ루ㅋㅋ-20442, 가짝연부-22862, 합이0인네정수-7453
  투포인터/ㅋㅋ루ㅋㅋ-20442/masonkimseoul.py
  투포인터/가짝연부-22862/masonkimseoul.py
  투포인터/합이0인네정수-7453/masonkimseoul.py
Labels: 투포인터

#28 [홍성철] / ㅋㅋ루ㅋㅋ-20442, 가짝연부-22862, 합이0인네정수-7453
  투포인터/ㅋㅋ루ㅋㅋ-20442/ironAiken2.py
  투포인터/가짝연부-22862/ironAiken2.py
  투포인터/합이0인네정수-7453/ironAiken2.py
Labels: 투포인터

#31 [김민수] / ㅋㅋ루ㅋㅋ-20442, 가짝연부-22862, 합이0인네정수-7453
  투포인터/ㅋㅋ루ㅋㅋ-20442/kmsu44.py
  투포인터/가짝연부-22862/kmsu44.py
  투포인터/합이0인네정수-7453/kmsu44.py
Labels: 투포인터

#29 [이우식] / ㅋㅋ루ㅋㅋ-20442, 가짝연부-22862, 합이0인네정수-7453
  투포인터/ㅋㅋ루ㅋㅋ-20442/yireal.py
  투포인터/가짝연부-22862/yireal.py
  투포인터/합이0인네정수-7453/yireal.py
Labels: 투포인터

#34 [홍성철] / 제자리멀리뛰기-6209, 카드팩 구매하기-15823, 휴게소 세우기-1477
  이분탐색/제자리멀리뛰기-6209/ironAiken2.py
  이분탐색/카드팩구매하기-15823/ironAiken2.py
  이분탐색/휴게소세우기-1477/ironAiken2.py
Labels: 이분탐색

#33 [김민수] / 제자리멀리뛰기-6209, 카드팩 구매하기-15823, 휴게소 세우기-1477
  이분탐색/제자리멀리뛰기-6209/kmsu44.py
  이분탐색/카드팩구매하기-15823/kmsu44.py
  이분탐색/휴게소세우기-1477/kmsu44.py
Labels: 이분탐색

#35 [홍성철] / 로또-2758, ACM Craft-1005, 꿈틀꿈틀 애벌레-20181
  DP/ACMCraft-1005/ironAiken2.py
  DP/꿈틀꿈틀애벌레-20181/ironAiken2.py
  DP/로또-2758/ironAiken2.py
Labels: DP

#36 [김민수] / 로또-2758, ACM Craft-1005, 꿈틀꿈틀 애벌레-20181
  DP/ACMCraft-1005/kmsu44.py
  DP/꿈틀꿈틀애벌레-20181/kmsu44.py
  DP/로또-2758/kmsu44.py
Labels: DP

#37 [이우식] / 로또-2758, ACM Craft-1005, 꿈틀꿈틀 애벌레-20181
  DP/ACMCraft-1005/yireal.py
  DP/꿈틀꿈틀애벌레-20181/yireal.py
  DP/로또-2758/yireal.py
  이분탐색/제자리멀리뛰기-6209/yireal.py
  이분탐색/휴게소세우기-1477/yireal.py
Labels: DP

#38 [김경원] / 로또-2758, ACM Craft-1005, 꿈틀꿈틀 애벌레-20181
  DP/ACMCraft-1005/masonkimseoul.py
  DP/꿈틀꿈틀애벌레-20181/masonkimseoul.py
  DP/로또-2758/masonkimseouil.py
Labels: DP
